---
functional:
  - Требование 1
  - Требование 3
  - Требование 4
  - Требование 8
  - Требование 9
non-functional:
  - Требование 2
  - Требование 5
  - Требование 6
  - Требование 7
  - Требование 10
implicit:
 - Не должно быть взможности заказать большее количество продукта чем есть в наличие
 - Продукты, которых больше нет в наличие не должны отображаться
 - Пользователь должен иметь возможность посмотреть свои заказы
 - Сумма должна считаться корректно
 
